server:
  port: 9080

spring:
  application:
    name: medical-server
  profiles:
    active: prod
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
  data:
    mongodb:
      host: 127.0.0.1
      database: medical
      username: medical
      password: 1234Qwer
      port: 27017
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

file:
  upload:
    path: /data/files/
  server:
    path: http://img.sswjjd.cn/
