server:
  port: 9080

spring:
  application:
    name: medical-server
  profiles:
    active: prod
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
  data:
    mongodb:
      host: 127.0.0.1
      database: medical
      username: medical
      password: 1234Qwer
      port: 27017

file:
  upload:
    path: /data/files/
  server:
    path: http://img.sswjjd.cn/

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 默认5分钟过期时间,单位毫秒。  300000 = 5 * 60  * 1000

